
services:
  elastic:
    container_name: elastic
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.1
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    networks:
      - elasticsearch-network
    ports:
      - 9200:9200

  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:8.11.1
    #restart: always
    environment:
      - ELASTICSEARCH_HOSTS=http://elastic:9200
    networks:
      - elasticsearch-network
    ports:
      - 5601:5601
    depends_on:
      - elastic
volumes:
    elasticsearch-data:
networks:
    elasticsearch-network:
